# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjFin-L1r3Hzkv8mIGw1JiwEXluvf_I7
"""

!pip install cryptography

!pip install cryptography

file1 = "History is the systematic study of the past"
file2 = "History is the systematic study of the past this is just for practice"

def jaccard_similarity(text1, text2):
    """
    Calculate the Jaccard similarity between two text strings.

    Args:
        text1 (str): The first text string.
        text2 (str): The second text string.

    Returns:
        tuple: A tuple containing the similarity score (float) and the set of common words.
    """
    set1 = set(text1.split())
    set2 = set(text2.split())

    intersection = set1.intersection(set2)
    union = set1.union(set2)

    similarity = len(intersection) / len(union)

    return similarity, intersection

text1 = " This is a sample sample text about is this legal sample issues."
text2 = " This text legal discusses legal and ethical This issues in legal computing."

similarity, common_words = jaccard_similarity(text1, text2)

print(f"similarity: {similarity:.2f}")
print(f"Common words: {common_words}")



from google.colab import drive
drive.mount('/content/drive')